// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.support;

import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.queries.EnumParam;

public enum UnblockScreenButtonUnblockFieldsType implements EnumParam {
    @SerializedName("unblock_button")
    UNBLOCK_BUTTON("unblock_button");

    private final String value;

    UnblockScreenButtonUnblockFieldsType(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return value.toLowerCase();
    }
}
