// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.prettycards.responses;

import com.google.gson.Gson;
import com.google.gson.JsonObject;
import com.vk.api.sdk.objects.base.Error;
import com.vk.api.sdk.objects.prettycards.PrettyCard;

public class GetByIdResponse {
    private JsonObject data;

    private Gson gson;

    public GetByIdResponse(JsonObject data) {
        this.data = data;
        gson = new Gson();
    }

    public JsonObject getRaw() {
        return data;
    }

    public PrettyCard getOneOf0() {
        return gson.fromJson(data.toString(), PrettyCard.class);
    }

    public Error getOneOf1() {
        return gson.fromJson(data.toString(), Error.class);
    }
}
