// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.stats;

import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.queries.EnumParam;

public enum GetInterval implements EnumParam {
    @SerializedName("all")
    ALL("all"),

    @SerializedName("day")
    DAY("day"),

    @SerializedName("month")
    MONTH("month"),

    @SerializedName("week")
    WEEK("week"),

    @SerializedName("year")
    YEAR("year");

    private final String value;

    GetInterval(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return value.toLowerCase();
    }
}
