// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.messages.responses;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.objects.Validable;
import com.vk.api.sdk.objects.annotations.Required;
import com.vk.api.sdk.objects.groups.GroupFull;
import com.vk.api.sdk.objects.messages.Conversation;
import com.vk.api.sdk.objects.users.UserFull;
import java.util.List;
import java.util.Objects;

/**
 * SearchConversationsExtendedResponse object
 */
public class SearchConversationsExtendedResponse implements Validable {
    /**
     * Total results number
     */
    @SerializedName("count")
    @Required
    private Integer count;

    @SerializedName("groups")
    private List<GroupFull> groups;

    @SerializedName("items")
    @Required
    private List<Conversation> items;

    @SerializedName("profiles")
    private List<UserFull> profiles;

    public Integer getCount() {
        return count;
    }

    public SearchConversationsExtendedResponse setCount(Integer count) {
        this.count = count;
        return this;
    }

    public List<GroupFull> getGroups() {
        return groups;
    }

    public SearchConversationsExtendedResponse setGroups(List<GroupFull> groups) {
        this.groups = groups;
        return this;
    }

    public List<Conversation> getItems() {
        return items;
    }

    public SearchConversationsExtendedResponse setItems(List<Conversation> items) {
        this.items = items;
        return this;
    }

    public List<UserFull> getProfiles() {
        return profiles;
    }

    public SearchConversationsExtendedResponse setProfiles(List<UserFull> profiles) {
        this.profiles = profiles;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(count, profiles, groups, items);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        SearchConversationsExtendedResponse searchConversationsExtendedResponse = (SearchConversationsExtendedResponse) o;
        return Objects.equals(count, searchConversationsExtendedResponse.count) &&
                Objects.equals(profiles, searchConversationsExtendedResponse.profiles) &&
                Objects.equals(groups, searchConversationsExtendedResponse.groups) &&
                Objects.equals(items, searchConversationsExtendedResponse.items);
    }

    @Override
    public String toString() {
        final Gson gson = new Gson();
        return gson.toJson(this);
    }

    public String toPrettyString() {
        final StringBuilder sb = new StringBuilder("SearchConversationsExtendedResponse{");
        sb.append("count=").append(count);
        sb.append(", profiles=").append(profiles);
        sb.append(", groups=").append(groups);
        sb.append(", items=").append(items);
        sb.append('}');
        return sb.toString();
    }
}
