// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

public class ApiAuthValidationException extends ApiException {
    public ApiAuthValidationException(String message) {
        super(17, "Validation required", message);
    }
}
