// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

public class ApiAuthValidationException extends ApiException {

    private final String redirectUri;

    public ApiAuthValidationException(String message, String redirectUri) {
        super(17, "Validation required", message);
        this.redirectUri = redirectUri;
    }

    public String getRedirectUri() {
        return redirectUri;
    }
}
