// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

public class ApiMarketGroupingMustHaveVariantsException extends ApiException {
    public ApiMarketGroupingMustHaveVariantsException(String message) {
        super(1415, "Grouping must have variants", message);
    }
}
