// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

public class ApiMarketMaxVariantsLimitExceedException extends ApiException {
    public ApiMarketMaxVariantsLimitExceedException(String message) {
        super(1419, "Max variant limit exceeded", message);
    }
}
