// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

public class ApiMessagesTooLongForwardsException extends ApiException {
    public ApiMessagesTooLongForwardsException(String message) {
        super(913, "Too many forwarded messages", message);
    }
}
