// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

public class ApiParamPhotoException extends ApiException {
    public ApiParamPhotoException(String message) {
        super(129, "Invalid photo", message);
    }
}
