// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.market;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.objects.Validable;
import java.util.List;
import java.util.Objects;

/**
 * MarketCategoryTreeView object
 */
public class MarketCategoryTreeView implements Validable {
    @SerializedName("root_path")
    private List<String> rootPath;

    @SerializedName("selected")
    private Boolean selected;

    @SerializedName("type")
    private MarketCategoryTreeViewType type;

    public List<String> getRootPath() {
        return rootPath;
    }

    public MarketCategoryTreeView setRootPath(List<String> rootPath) {
        this.rootPath = rootPath;
        return this;
    }

    public Boolean getSelected() {
        return selected;
    }

    public MarketCategoryTreeView setSelected(Boolean selected) {
        this.selected = selected;
        return this;
    }

    public MarketCategoryTreeViewType getType() {
        return type;
    }

    public MarketCategoryTreeView setType(MarketCategoryTreeViewType type) {
        this.type = type;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(rootPath, type, selected);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        MarketCategoryTreeView marketCategoryTreeView = (MarketCategoryTreeView) o;
        return Objects.equals(rootPath, marketCategoryTreeView.rootPath) &&
                Objects.equals(type, marketCategoryTreeView.type) &&
                Objects.equals(selected, marketCategoryTreeView.selected);
    }

    @Override
    public String toString() {
        final Gson gson = new Gson();
        return gson.toJson(this);
    }

    public String toPrettyString() {
        final StringBuilder sb = new StringBuilder("MarketCategoryTreeView{");
        sb.append("rootPath='").append(rootPath).append("'");
        sb.append(", type='").append(type).append("'");
        sb.append(", selected=").append(selected);
        sb.append('}');
        return sb.toString();
    }
}
