// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.ads;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.objects.Validable;
import java.util.Objects;

/**
 * ClipItem object
 */
public class ClipItem implements Validable {
    @SerializedName("link")
    private ClipItemLink link;

    /**
     * Preview url
     */
    @SerializedName("preview_url")
    private String previewUrl;

    /**
     * Video id
     */
    @SerializedName("video_id")
    private Integer videoId;

    public ClipItemLink getLink() {
        return link;
    }

    public ClipItem setLink(ClipItemLink link) {
        this.link = link;
        return this;
    }

    public String getPreviewUrl() {
        return previewUrl;
    }

    public ClipItem setPreviewUrl(String previewUrl) {
        this.previewUrl = previewUrl;
        return this;
    }

    public Integer getVideoId() {
        return videoId;
    }

    public ClipItem setVideoId(Integer videoId) {
        this.videoId = videoId;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(previewUrl, link, videoId);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ClipItem clipItem = (ClipItem) o;
        return Objects.equals(previewUrl, clipItem.previewUrl) &&
                Objects.equals(link, clipItem.link) &&
                Objects.equals(videoId, clipItem.videoId);
    }

    @Override
    public String toString() {
        final Gson gson = new Gson();
        return gson.toJson(this);
    }

    public String toPrettyString() {
        final StringBuilder sb = new StringBuilder("ClipItem{");
        sb.append("previewUrl='").append(previewUrl).append("'");
        sb.append(", link=").append(link);
        sb.append(", videoId=").append(videoId);
        sb.append('}');
        return sb.toString();
    }
}
