// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.newsfeed;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.objects.Validable;
import java.util.Objects;

/**
 * ItemVideo object
 */
public class ItemVideo extends ItemBase implements Validable {
    /**
     * Index of current carousel element
     */
    @SerializedName("carousel_offset")
    private Integer carouselOffset;

    /**
     * Post ID
     */
    @SerializedName("post_id")
    private Integer postId;

    @SerializedName("video")
    private ItemVideoVideo video;

    public Integer getCarouselOffset() {
        return carouselOffset;
    }

    public ItemVideo setCarouselOffset(Integer carouselOffset) {
        this.carouselOffset = carouselOffset;
        return this;
    }

    public Integer getPostId() {
        return postId;
    }

    public ItemVideo setPostId(Integer postId) {
        this.postId = postId;
        return this;
    }

    public ItemVideoVideo getVideo() {
        return video;
    }

    public ItemVideo setVideo(ItemVideoVideo video) {
        this.video = video;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(carouselOffset, postId, video);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ItemVideo itemVideo = (ItemVideo) o;
        return Objects.equals(postId, itemVideo.postId) &&
                Objects.equals(video, itemVideo.video) &&
                Objects.equals(carouselOffset, itemVideo.carouselOffset);
    }

    @Override
    public String toString() {
        final Gson gson = new Gson();
        return gson.toJson(this);
    }

    public String toPrettyString() {
        final StringBuilder sb = new StringBuilder("ItemVideo{");
        sb.append("postId=").append(postId);
        sb.append(", video=").append(video);
        sb.append(", carouselOffset=").append(carouselOffset);
        sb.append('}');
        return sb.toString();
    }
}
